######################################################################
# Automatically generated by qmake (1.07a) Mon Jan 30 17:02:55 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
