######################################################################
# Automatically generated by qmake (1.07a) Sat Sep 9 20:00:06 2006
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += blowfish.cpp
