######################################################################
# Automatically generated by qmake (1.07a) ?? 21. ??? 21:09:55 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += itdialog.h mainform.h
SOURCES += itdialog.cpp main.cpp mainform.cpp
