######################################################################
# Automatically generated by qmake (1.07a) Mon Feb 6 15:45:33 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
IMAGES += images/journal.bmp 
#         images/power0000.bmp \
#          images/power0001.bmp \
#          images/power0002.bmp
          
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
