######################################################################
# Automatically generated by qmake (1.07a) Fri Sep 15 23:16:16 2006
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
