######################################################################
# Automatically generated by qmake (1.07a) Sat Jan 14 19:30:29 2006
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += rc4.h
SOURCES += main.cpp rc4.cpp
